[phases.setup]
aptPkgs = [
    "python3",
    "python3-pip",
    "make",
    "g++",
    "gcc"
]

[phases.install]
cmds = [
    "npm install -g @mapbox/node-pre-gyp",
    "export PATH=/usr/local/bin:$PATH",  # Ensure pip is in PATH
    "npm ci --only=production"           # Use ci instead of install for cleaner builds
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
