[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[build.buildEnv]
NODE_ENV = "production"

# Required packages for mediasoup
[[build.nixpacks.aptPackages]]
name = "python3"
[[build.nixpacks.aptPackages]]
name = "python3-pip"
[[build.nixpacks.aptPackages]]
name = "make"
[[build.nixpacks.aptPackages]]
name = "gcc"
[[build.nixpacks.aptPackages]]
name = "g++"
